name: Deploy Service

on: 
  push:
    branches:
      - main
    tags:
      - 'v*'

env:
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  ARTIFACT_REGISTRY_REPOSITORY: ${{ secrets.ARTIFACT_REGISTRY_REPOSITORY }}
  ARTIFACT_REGISTRY: ${{ secrets.ARTIFACT_REGISTRY }}
  CLOUD_RUN_REGION: ${{ secrets.CLOUD_RUN_REGION }}
  IMAGE_TAG: ${{ github.sha }}
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:

  build:

    name: We-Up Instance Deployment
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          version: 'latest'
          project_id: ${{ env.PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_CI_PROD_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_CI_PROD_SA_KEY_BASE64 }}
          
      - name: base64-to-file
        id: write_file
        uses: timheuer/base64-to-file@v1.2 
        with:
          # Name of the file when written to temp location
          fileName: 'key.json'
          # The base64 encoded string
          encodedString: ${{ secrets.GCP_CI_PROD_SA_KEY_BASE64 }}

      - name: Configure Docker
        run: |
          gcloud auth configure-docker $ARTIFACT_REGISTRY
      - name: Load envs and save to .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_API_ROOT_PATH:  ${{ secrets.API_ROOT_PATH }}
          # envkey_GOOGLE_CONFIG_BASE64:  ${{ secrets.GOOGLE_CONFIG_BASE64 }}
          # envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          # fail_on_empty: true
          VITE_API_URL: ${{ secrets.API_URL }}
          VITE_SUPPORT_EMAIL: ${{ secrets.SUPPORT_EMAIL }}
          file_name: .env
          
      - name: Build
        # env:
        #   DOCKER_IMAGE_TAG: ${{ github.ref }}
        run: |
          docker build -t $ARTIFACT_REGISTRY/$PROJECT_ID/$ARTIFACT_REGISTRY_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG -t $ARTIFACT_REGISTRY/$PROJECT_ID/$ARTIFACT_REGISTRY_REPOSITORY/$IMAGE_NAME:latest .
          # docker build -t $ARTIFACT_REGISTRY/$PROJECT_ID/$ARTIFACT_REGISTRY_REPOSITORY/$IMAGE_NAME:${DOCKER_IMAGE_TAG} .
          
      - name: Output Docker Images
        run: |
          docker images
      - name: Authenticating Artifact Repository
        run: |
          cat ${{ steps.write_file.outputs.filePath }} | docker login -u _json_key --password-stdin https://$ARTIFACT_REGISTRY
      - name: Push
        # env:
        #   DOCKER_IMAGE_TAG: ${{ github.ref }}
        run: |
          docker push -a $ARTIFACT_REGISTRY/$PROJECT_ID/$ARTIFACT_REGISTRY_REPOSITORY/$IMAGE_NAME
          # docker push $ARTIFACT_REGISTRY/$PROJECT_ID/$ARTIFACT_REGISTRY_REPOSITORY/$IMAGE_NAME:${DOCKER_IMAGE_TAG}
      - name: Deploy To we-up Cloud Run Instance
        run: |
          gcloud run deploy we-up --image $ARTIFACT_REGISTRY/$PROJECT_ID/$ARTIFACT_REGISTRY_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG --project ${{ env.PROJECT_ID }} --platform managed --region $CLOUD_RUN_REGION --allow-unauthenticated
          
